#!/usr/bin/env node
/*
 * Regenerates the registration list in generator/src/index.ts.
 *
 * Run this once after adding or removing a generator:
 *     node scripts/gen-index.js
 *
 * Keys are the file names with the `.ts` stripped, because dispatch looks
 * generators up by AST node type / library name.
 */
const fs = require("fs");
const path = require("path");

const src = path.join(__dirname, "..", "src");
const list = (dir) =>
    fs.readdirSync(dir)
        .filter((f) => f.endsWith(".ts") && f !== "index.ts")
        .map((f) => f.slice(0, -3))
        .sort();

const stmts = list(path.join(src, "generator"));
const types_ = list(path.join(src, "generator", "types"));
const blibs = list(path.join(src, "generator", "CallExpressionSub"));
const vlibs = list(path.join(src, "generator", "types", "CallExpressionSub"));

const block = (label, fn, arg, names, sub) => {
    const head = `// ---- ${label} (${names.length}) ----`;
    const body = names.map((n) =>
        arg
            ? `${fn}("${arg}", "${n}", require("./generator/${sub}${n}"));`
            : `${fn}("${n}", require("./generator/${sub}${n}"));`
    );
    return [head, ...body].join("\n");
};

const total = stmts.length + types_.length + blibs.length + vlibs.length;

// The banner and the doc block below are emitted verbatim so that re-running
// this script reproduces src/index.ts exactly. Keep them in sync with the
// committed file — anything missing here is silently deleted on regeneration.
const banner = `/*******************************************************************
* Copyright         : 2024 saaawdust
* File Name         : index.ts
* Description       : Generator entry — registers every impl into core's registry
*
* Revision History  :
* Date        Author          Comments
* ------------------------------------------------------------------
* 09/19/2026  NeuronPulse     Added — registry-based dispatch
/******************************************************************/`;

const doc = `/**
 * Entry point for \`@jvavscratch/generator\`. **Importing it registers every
 * generator.**
 *
 * core cannot statically depend on generator (the dependency direction is
 * types ← core ← utils ← generator), so this package is the one that pushes
 * all the generators into \`@jvavscratch/core\`'s dispatch tables at load time.
 * core used to assemble a path with \`require(join(__dirname, "../generator/"
 * + node.type))\`; once the repository was split apart that path could only
 * ever point at nothing. Now that dispatch goes through a registry, both
 * sides refer to generators purely by name.
 *
 * Using \`require\` here rather than \`import\` is deliberate: each generator is
 * CommonJS in the \`module.exports = fn\` form, and \`import x from\` makes tsc
 * report TS1192 (the module has no default export). See the "Module format"
 * section of CLAUDE.md.
 *
 * This file is generated by \`scripts/gen-index.js\`; re-run it whenever a
 * generator is added.
 */`;

const out = `${banner}

${doc}

import {
    registerStatement,
    registerType,
    registerLibrary,
} from "@jvavscratch/core";

// ${total} implementations are registered in total: ${stmts.length} statement
// generators + ${types_.length} value generators + ${blibs.length} block libraries + ${vlibs.length} value libraries.

${block("Statement generators", "registerStatement", null, stmts, "")}

${block("Value generators", "registerType", null, types_, "types/")}

${block("Block libraries", "registerLibrary", "block", blibs, "CallExpressionSub/")}

${block("Value libraries", "registerLibrary", "value", vlibs, "types/CallExpressionSub/")}

export * from "./optimise";
`;

fs.writeFileSync(path.join(src, "index.ts"), out);
console.log(`Regenerated generator/src/index.ts with ${total} implementations.`);
