/*******************************************************************
* Copyright         : 2024 saaawdust
* File Name         : index.ts
* Description       : Generator entry — registers every impl into core's registry
*
* Revision History  :
* Date        Author          Comments
* ------------------------------------------------------------------
* 09/19/2026  NeuronPulse     Added — registry-based dispatch
/******************************************************************/

/**
 * Entry point for `@jvavscratch/generator`. **Importing it registers every
 * generator.**
 *
 * core cannot statically depend on generator (the dependency direction is
 * types ← core ← utils ← generator), so this package is the one that pushes
 * all the generators into `@jvavscratch/core`'s dispatch tables at load time.
 * core used to assemble a path with `require(join(__dirname, "../generator/"
 * + node.type))`; once the repository was split apart that path could only
 * ever point at nothing. Now that dispatch goes through a registry, both
 * sides refer to generators purely by name.
 *
 * Using `require` here rather than `import` is deliberate: each generator is
 * CommonJS in the `module.exports = fn` form, and `import x from` makes tsc
 * report TS1192 (the module has no default export). See the "Module format"
 * section of CLAUDE.md.
 *
 * This file is generated by `scripts/gen-index.js`; re-run it whenever a
 * generator is added.
 */

import {
    registerStatement,
    registerType,
    registerLibrary,
} from "@jvavscratch/core";

// 42 implementations are registered in total: 13 statement
// generators + 10 value generators + 10 block libraries + 9 value libraries.

// ---- Statement generators (13) ----
registerStatement("AssignmentExpression", require("./generator/AssignmentExpression"));
registerStatement("AwaitExpression", require("./generator/AwaitExpression"));
registerStatement("CallExpression", require("./generator/CallExpression"));
registerStatement("ClassDeclaration", require("./generator/ClassDeclaration"));
registerStatement("ExpressionStatement", require("./generator/ExpressionStatement"));
registerStatement("ForStatement", require("./generator/ForStatement"));
registerStatement("FunctionDeclaration", require("./generator/FunctionDeclaration"));
registerStatement("IfStatement", require("./generator/IfStatement"));
registerStatement("ReturnStatement", require("./generator/ReturnStatement"));
registerStatement("SwitchStatement", require("./generator/SwitchStatement"));
registerStatement("UpdateExpression", require("./generator/UpdateExpression"));
registerStatement("VariableDeclaration", require("./generator/VariableDeclaration"));
registerStatement("WhileStatement", require("./generator/WhileStatement"));

// ---- Value generators (10) ----
registerType("BinaryExpression", require("./generator/types/BinaryExpression"));
registerType("BooleanLiteral", require("./generator/types/BooleanLiteral"));
registerType("CallExpression", require("./generator/types/CallExpression"));
registerType("Identifier", require("./generator/types/Identifier"));
registerType("LogicalExpression", require("./generator/types/LogicalExpression"));
registerType("MemberExpression", require("./generator/types/MemberExpression"));
registerType("NewExpression", require("./generator/types/NewExpression"));
registerType("NumericLiteral", require("./generator/types/NumericLiteral"));
registerType("StringLiteral", require("./generator/types/StringLiteral"));
registerType("UnaryExpression", require("./generator/types/UnaryExpression"));

// ---- Block libraries (10) ----
registerLibrary("block", "broadcast", require("./generator/CallExpressionSub/broadcast"));
registerLibrary("block", "control", require("./generator/CallExpressionSub/control"));
registerLibrary("block", "list", require("./generator/CallExpressionSub/list"));
registerLibrary("block", "looks", require("./generator/CallExpressionSub/looks"));
registerLibrary("block", "method", require("./generator/CallExpressionSub/method"));
registerLibrary("block", "motion", require("./generator/CallExpressionSub/motion"));
registerLibrary("block", "pen", require("./generator/CallExpressionSub/pen"));
registerLibrary("block", "sensing", require("./generator/CallExpressionSub/sensing"));
registerLibrary("block", "sound", require("./generator/CallExpressionSub/sound"));
registerLibrary("block", "variable", require("./generator/CallExpressionSub/variable"));

// ---- Value libraries (9) ----
registerLibrary("value", "list", require("./generator/types/CallExpressionSub/list"));
registerLibrary("value", "looks", require("./generator/types/CallExpressionSub/looks"));
registerLibrary("value", "math", require("./generator/types/CallExpressionSub/math"));
registerLibrary("value", "method", require("./generator/types/CallExpressionSub/method"));
registerLibrary("value", "motion", require("./generator/types/CallExpressionSub/motion"));
registerLibrary("value", "operation", require("./generator/types/CallExpressionSub/operation"));
registerLibrary("value", "sensing", require("./generator/types/CallExpressionSub/sensing"));
registerLibrary("value", "sound", require("./generator/types/CallExpressionSub/sound"));
registerLibrary("value", "util", require("./generator/types/CallExpressionSub/util"));

export * from "./optimise";
